import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import Explore from '../components/Explore'
import Footer from '../components/Footer'
import Header from '../components/Header'
import LargeCard from '../components/LargeCard'
import Randomlive from '../components/Randomlive'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      {/* Topbar */}
      <Head>
        <title>Airbnb Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <Header/>
      {/* <Header/>=> self closed componenet */}
      <Banner/>
      <main className='max-w-7xl mx-auto px-8 sm:px-16'>
        <section className='pt-6'>
          <Explore/>
          {/*Pull some data from server-api*/ }
        </section>
        <section>
          <Randomlive/>
        </section>
        <LargeCard/>
      </main>
      <Footer/>
    </div>
  )
}

